# SuggarChat 使用 LongCat 模型（models/longcat.json）
preset = "longcat"
enable = true

[default_preset]
model = "LongCat-Flash-Thinking"
name = "default"
base_url = "https://api.longcat.chat/openai"
api_key = "ak_24x7Xc6Vc2YC2Uw7212bw4pt3Eg8W"
protocol = "openai"
thought_chain_model = false
multimodal = false
 